### ISSUE TITLE
API version incompatible.

### ISSUE THREAD

**Issue by Yanivro** [gbowerman/azurerm#14]
When trying to get vm nics(get_vmss_vms_nics) I get the following error:
"No registered resource provider found for location 'westeurope' and API version '2017-03-30' for type 'virtualMachineScaleSets/virtualMachines/netw
orkInterfaces'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01'

Maybe make API version override-able?

**Comment by gbowerman** [comment]
Thanks for reporting this. Fixed in 46bfbbd (azurerm 0.7.20)

**Comment by gbowerman** [comment]
Closing this issue for now, though on a related note I'd like to implement API version override using environment variables (e.g. set an environment variable to override version, and an environment variable to override endpoint URL in order to work with national clouds). @Yanivro do you think that would be a good way to do it, or better to have optional function arguments with API version?

**Comment by Yanivro** [comment]
@gbowerman I think since each sub resource might work with a different API version, it might be better to pass that argument for each function, hence not "forcing" people using the lib to use a newer API version that might have changed something and break their code.
