### ISSUE TITLE
list_vms_sub returns a maximum of 50 results

### ISSUE THREAD

**Issue by jgoldschrafe** [gbowerman/azurerm#6]
The `list_vms_sub` function returns a maximum of 50 results. To return more than 50 results using the azurerm module, the resource groups must be enumerated, and `list_vms` must be called for each returned resource group. (`list_vms_sub` does not itself have this issue; it will happily return 51+ VMs from a single resource group.)

 For short scripts, it would be nice to see `list_vms` return all results, or at least a configurable maximum.

**Comment by gbowerman** [comment]
Thanks for pointing this out @jgoldschrafe - I was not aware the REST call to list VMs in a subscription was capped at 50, and it doesn't appear to be documented. I'll see if I can find out more about that limitation. I'd like to keep the list_vms_sub() function in azurerm as light as possible and have it remain  just  wrapper to the underlying REST call, since having to loop through the resource groups would slow the call down, and there is a workaround. However if the underlying limit can't be removed, I'll make sure the 50 VM limit for this call is documented.

**Comment by gbowerman** [comment]
@jgoldschrafe when you call kist_vms_sub() against >50 VMs and dump the JSON output, does it finish with a "nextLink":  property? If it does, then I know how to fix it (i.e. call the REST api in a loop until there are no more nextLink pointers), and should have it turned around by EOW.

**Comment by gbowerman** [comment]
@jgoldschrafe fixed the issue by following the nextLink chain in list_vms_sub(). It should be working now. Thanks for raising this issue. As a follow up I will try and get a list of all the functions which have a nextLink chain and make a generic list function for them. Closing this issue as the list_vms_sub() issue is fixed.

**Comment by gbowerman** [comment]
@jgoldschrafe - the library has now been updated to support all Compute functions which return nextLink: list VMs in a subscription, list availability sets in a subscription, list scale sets in a subscription, list scale sets in a resource group. Added a generic do_get_next() function which these functions can call. Thanks again for logging it.
